name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add write permisions to sdk
        run: sudo chmod -R a+w /usr/local/lib/android/sdk
      - name: Add client gradlew permissions
        run: cd client && chmod +x ./gradlew
      - name: Add server gradlew permissions
        run: cd server && chmod +x ./gradlew
      - name: Unit tests client
        run: cd client && ./gradlew test --stacktrace
      - name: Unit tests server
        run: cd server && ./gradlew test --stacktrace
