name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add write permisions to sdk
        run: sudo chmod -R a+w /usr/local/lib/android/sdk
      - name: Go to client dir
        run: cd client
      - name: Unit tests client
        run: ./gradlew test --stacktrace
      - name: Go to sever dir
        run: cd ../server
      - name: Unit tests server
        run: ./gradlew test --stacktrace
